spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      default-filters:
        - Custom=true
      routes:
        - id: test_consumer_service
          uri: lb://SC-CONSUMER
          order: 0
          predicates:
             - Path=/test/prefix/**
          filters:
             - StripPrefix=2
             - AddResponseHeader=X-Response-test, test

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug